#!/usr/bin/env python3
"""Re-derive character_drops.json from THIS repo's own roster data.

The rule (user, 2026-07-25): a character with fewer than six fully-evolved
Pokemon obtainable in this game is not offered here -- unless a legendary or
mythical is on the roster, which exempts them. They keep their table slot and are
hidden from the menu, because saves store the character INDEX and deleting a row
would repoint every existing save at a different character.

Why this script exists: the drop list was originally computed by the audit's
`per_game_threshold.py`, which reads the audit's `final_rosters.json`. That file
does NOT include this repo's `roster_additions.json` overlay or wave 5, so its
answer drifts from what the ROM actually enforces in BOTH directions -- applying
it verbatim to ROWE left 20 Legends: Arceus wardens selectable with a single final
evolution each, while hiding 5 characters who clear the bar once their overlay
adds count.

So: expand each roster with `emit_bitmaps.expand_roster` (the very function that
builds the injected allow-bitmaps) and count finals with
`emit_roster_docs.is_final`'s rules (the very walk that writes the doc rows).
Sharing both means the threshold, the bitmaps and the docs cannot disagree about
who is thin.

Run BEFORE emit_characters.py; it rewrites character_drops.json in place.
"""
import argparse
import json
import re
from pathlib import Path

import emit_bitmaps
import emit_roster_docs
from map_species import LEGENDARY_NAMES, normalize

HERE = Path(__file__).parent
EVO_METHOD_MEGA = emit_roster_docs.EVO_METHOD_MEGA
LEGENDARY_NORM = {normalize(n) for n in LEGENDARY_NAMES}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="report only; do not rewrite character_drops.json")
    args = ap.parse_args()

    species = emit_bitmaps.load_species()
    evolves_to, ids_by_name = emit_bitmaps.build_indexes(species)
    with open(HERE / "rosters_mapped.json") as f:
        mapped = json.load(f)

    # "final evolution" exactly as emit_roster_docs counts it: mega evolution
    # (method 254) is a battle transformation, not an evolution, and a cosmetic
    # form whose base still evolves is not a final stage.
    real_evos = {}
    for sid, info in species.items():
        real_evos[sid] = [e[2] for e in (info.get("evolutions") or [])
                          if len(e) >= 3 and e[0] != EVO_METHOD_MEGA
                          and e[2] in species]

    def dex_of(sid):
        return species[sid].get("dexID") or sid

    canonical = {}
    for sid in sorted(species):
        canonical.setdefault(dex_of(sid), sid)

    def is_final(sid):
        if real_evos.get(sid):
            return False
        base = canonical.get(dex_of(sid), sid)
        return not real_evos.get(base)

    def shown_row(sid):
        """The doc row this final collapses onto: a regional form keeps its own
        row, everything else folds into the base sharing its dex number."""
        if emit_roster_docs.regional_form(species[sid]):
            return sid
        return canonical.get(dex_of(sid), sid)

    dropped, kept, exempt = [], [], []
    for char, info in sorted(mapped.items()):
        name = re.sub(r"\s*\(anime\)$", "", char)
        ids = [s["id"] for s in info["species"]]
        if any(normalize(s["name"]) in LEGENDARY_NORM for s in info["species"]):
            exempt.append(name)
            kept.append(name)
            continue
        allowed = emit_bitmaps.expand_roster(ids, species, evolves_to, ids_by_name)
        finals = {shown_row(s) for s in allowed if is_final(s)}
        if len(finals) < 6:
            dropped.append((name, len(finals)))
        else:
            kept.append(name)

    path = HERE / "character_drops.json"
    old = set()
    if path.is_file():
        with open(path) as f:
            old = set(json.load(f).get("unselectable", []))
    new = sorted(n for n, _ in dropped)

    if not args.dry_run:
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"_comment": "Characters that stay in the table (saves "
                                   "store the INDEX) but fall under the "
                                   "six-fully-evolved threshold in this game's "
                                   "dex, with no legendary to exempt them. "
                                   "GENERATED by derive_drops.py -- do not "
                                   "hand-edit.",
                       "unselectable": new}, f, indent=1, sort_keys=True,
                      ensure_ascii=False)
            f.write("\n")

    print("%d characters: %d clear the threshold (%d of them by legendary "
          "exemption), %d fall under it"
          % (len(mapped), len(kept), len(exempt), len(new)))
    for n, c in sorted(dropped, key=lambda x: (x[1], x[0])):
        print("   %-18s %d final%s" % (n, c, "" if c == 1 else "s"))
    for n in sorted(set(new) - old):
        print("   + newly under threshold: %s" % n)
    for n in sorted(old - set(new)):
        print("   - now clears threshold:  %s" % n)
    if args.dry_run:
        print("(dry run -- character_drops.json not rewritten)")


if __name__ == "__main__":
    main()
