#!/usr/bin/env python3
"""Resolve CFRU hook symbols to their real compiled addresses in the RR ROM.

CFRU's build installs each of its C functions by overwriting a known vanilla
FireRed address with a Thumb trampoline (`ldr rX, [pc, #imm]; bx rX` +
4-byte literal). The `hooks` file in the CFRU source tree records
"<FunctionName> <vanilla_address> <type>" for every one of them. Radical Red
kept this mechanism (verified: ScriptGiveMon's trampoline at its recorded
vanilla address 0x080A011C resolves to 0x0907767D, whose decompilation
matches CFRU's source line for line — see docs/ROUTINE_MAP.md).

So: reading the trampoline literal at each recorded vanilla address yields
Radical Red's compiled address for (almost) every CFRU function — a
539-entry symbol table for free, no disassembly needed.

Unresolved entries are ones whose first halfword isn't a pc-relative ldr
(different hook type, e.g. mid-function byte patches rather than whole-
function replacement) — listed at the bottom of the output for the record.

Usage: resolve_cfru_hooks.py
Reads:  rom/radicalred 4.1.gba, tools/cfru_donor/hooks
Writes: docs/CFRU_HOOK_SYMBOLS.txt
"""
import re
import struct
from pathlib import Path

HERE = Path(__file__).parent
ROM = HERE.parent / "rom" / "radicalred 4.1.gba"
HOOKS = HERE / "cfru_donor" / "hooks"
OUT = HERE.parent / "docs" / "CFRU_HOOK_SYMBOLS.txt"


def main():
    data = ROM.read_bytes()

    hooks = []
    with open(HOOKS) as f:
        for line in f:
            line = line.split("#")[0].strip()
            m = re.match(r"^(\w+)\s+([0-9A-Fa-f]{6,8})(\s+\d+)?$", line)
            if m:
                hooks.append((m.group(1), int(m.group(2), 16)))

    resolved, unresolved = [], []
    for name, vaddr in hooks:
        off = vaddr - 0x8000000
        if off < 0 or off + 8 > len(data):
            unresolved.append((name, vaddr, "vanilla address out of ROM range"))
            continue
        hw = struct.unpack_from("<H", data, off)[0]
        if (hw & 0xF800) == 0x4800:  # ldr rd, [pc, #imm]
            imm = (hw & 0xFF) * 4
            lit_addr = ((off + 4) & ~3) + imm
            v = struct.unpack_from("<I", data, lit_addr)[0]
            if 0x08000000 <= v <= 0x09FFFFFF and (v & 1):
                resolved.append((name, vaddr, v))
                continue
            unresolved.append((name, vaddr, f"literal 0x{v:08X} not a Thumb code pointer"))
        else:
            unresolved.append((name, vaddr, f"no pc-relative ldr at hook site (first hw 0x{hw:04X})"))

    with open(OUT, "w") as f:
        f.write("# CFRU hook symbols resolved against Radical Red v4.1\n")
        f.write(f"# ROM pinned by ../rom.sha1. Generated by tools/resolve_cfru_hooks.py — do not hand-edit.\n")
        f.write(f"# {len(resolved)} resolved, {len(unresolved)} unresolved (of {len(hooks)} hooks)\n")
        f.write("#\n# name  vanilla_hook_addr  rr_compiled_addr (Thumb bit set)\n\n")
        for name, vaddr, v in resolved:
            f.write(f"{name:55s} 0x{vaddr:08X}  0x{v:08X}\n")
        f.write("\n# --- unresolved (hook exists but isn't a whole-function trampoline) ---\n")
        for name, vaddr, why in unresolved:
            f.write(f"# {name:53s} 0x{vaddr:08X}  {why}\n")

    print(f"resolved {len(resolved)}/{len(hooks)} hooks -> {OUT}")
    for probe in ("ScriptGiveMon", "SendMonToPC", "CalculatePlayerPartyCount"):
        hit = next((v for n, _, v in resolved if n == probe), None)
        print(f"  sanity {probe}: {'0x%08X' % hit if hit else 'NOT RESOLVED'}")


if __name__ == "__main__":
    main()
